language: en

pipeline:
   - name: WhitespaceTokenizer
     intent_tokenization_flag: true
     intent_split_symbol: "+"
   - name: KeywordIntentClassifier
     epochs: 100
   - name: CRFEntityExtractor
# doesnt work with to much data because finds to many duplicated keywords
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
